###
@url=https://myweb-dotnet.huynguyen.xyz/api/
# @url=http://localhost:5000/api/
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imh1eW52cEBnbWFpbC5jb20iLCJpYXQiOiJhSFY1Ym5ad1FHZHRZV2xzTG1OdmJRPT0iLCJleHAiOjE1Nzc0NjIyNDQsIm5iZiI6MTU3NzQ1ODY0NCwiaXNzIjoiaHR0cHM6Ly9teXdlYi1kb3RuZXQuaHV5bmd1eWVuLnh5ei8iLCJhdWQiOiJodHRwczovL215d2ViLWRvdG5ldC5odXluZ3V5ZW4ueHl6LyJ9.TfUwDTDWGOvt0CcE3wX6UBkNpjBRhPxVs0r_jxiROF8
@refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imh1eW52cEBnbWFpbC5jb20iLCJpYXQiOiJiV3hvYUVGSVNqaGpjREJYTkdjd2IwNU1VMlo1WmtGdGFVcHlVR2hxTUZKb1V6azBaR0l6WjNwWk1HRTRhbUpMWVhWUVpYVmtaa1phUkdKT2VHdzFUMUJKTnpkbGRnPT0iLCJleHAiOjE1NzcxMTQ3MjQsIm5iZiI6MTU3NjUwOTkyNCwiaXNzIjoiaHR0cHM6Ly9teXdlYi1kb3RuZXQuaHV5bmd1eWVuLnh5ei8iLCJhdWQiOiJodHRwczovL215d2ViLWRvdG5ldC5odXluZ3V5ZW4ueHl6LyJ9.GcIig-4tnJYddJ-8LZo3SounM4D_K0rqXGBvz6LDN4A

###
POST  {{url}}user/login Http/1.1
Content-Type: application/json

{
    "username": "huynvp@gmail.com",
    "password": "112233"
}

###

PUT {{url}}user/refresh-token Http/1.1
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}

###
GET {{url}}projectLogs Http/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{url}}projectLogs Http/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "MyWeb_Localhost",
    "status": 1
}

###
POST {{url}}projectLogs/XB35-T4N4-B2IR-QVBT-UK3G-KD6J/logs Http/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "MyWeb_Localhost",
    "type": 1
}

###
GET {{url}}projectLogs/XB35-T4N4-B2IR-QVBT-UK3G-KD6J/logs Http/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "MyWeb_Localhost",
    "type": 1
}

###
DELETE  {{url}}projectLogs/XB35-T4N4-B2IR-QVBT-UK3G-KD6J/logs/5de7d4823d9427048f436bc9 Http/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
DELETE  {{url}}projectLogs/XB35-T4N4-B2IR-QVBT-UK3G-KD6J/logs Http/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Id": [
        "5de7d4ae3d9427048f436bca",
        "5de7d4af3d9427048f436bcb",
        "5de3fb78cbf6b70594da7a4e",
        "5de3fb82cbf6b70594da7a4f"
    ]
}


###
DELETE {{url}}projectLogs/5dd6b44e3fa58d057ba2525b Http/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{url}}admin/messageLogs Http/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
DELETE  {{url}}admin/messageLogs/1 Http/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

#ToDoList
###
GET {{url}}toDoList Http/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{url}}toDoList/1 Http/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST  {{url}}toDoList Http/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Content": "Test content",
    "DateStart": "2019-12-20",
    "DateEnd": "2019-12-29"
}